* *emacs.d*
  This is my GNU Emacs configuration.
  This is a _work in progress_.

** What is present?
   - Highly configured for C programming with gtk+
   - includes
     - yasnippet (powerful snippets)
     - ido
     - company (autocompletion)
     - flycheck (check syntax -- configured for gcc)
     - web-mode
     - avy
     - key-chord
     - ...

** How can I use this?
   Just copy =.emacs.d= to your home dir. If you already have a =.emacs=
   file in your home dir [re]move it. Otherwise this configuration won't work.

   By default, every mode is read only, with vi like bindings.
   - see =less-evil-mode.el= file to see the bindings.
   - see =init-keys.el= to see normal keyboard bindings

** Why is this insanely configured?

   This is configured for me. If you don't like this, this is not for you.

* License

  Copyright (c) 2016 Mohammed Sadiq <sadiq@sadiqpk.org>

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but *without any warranty*; without even the implied warranty of
  *merchantability* or *fitness for a particular purpose*.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see [[http://www.gnu.org/licenses/]].
