* *emacs.d*
  This is my GNU Emacs configuration.
  This is a _work in progress_.

  Everything is configured with the idea of dwim (do what I mean).
  Many codes are mere hacks. Some are very dirty hacks around
  =font-lock-mode=. So don't expect this to work consistantly right.
  You have been warned. =;-)=

  Happy Hacking.

** What is present?
   - Highly configured for C programming with gtk+
   - Highly configured for javascript programming
   - Highly personalised vi like mode (less-evil-mode)
     - Enabled when read-only enabled (=C-x C-q=)
   - includes
     - yasnippet (powerful snippets)
     - ido
     - company (autocompletion)
       - install =tern= npm package for javascript
     - flycheck (check syntax -- configured for gcc)
       - install =jshint= npm package for javascript
     - highlight diffs (in vcs like git) using diff-hl-mode
     - web-mode
     - js2-mode
     - avy
     - key-chord
     - ...

*** *important*
    <return> and <backspace> won't work the usual way.
    use =C-m= and =C-h= for that respectively.

** How can I use this?
   Just copy =.emacs.d= to your home dir. If you already have a =.emacs=
   file in your home dir [re]move it. Otherwise this configuration won't work.
   When running for the first time, GNU Emacs shall use internet to download
   and install missing packages.

   By default, every mode is read only, with vi like bindings.
   - see =less-evil-mode.el= file to see the bindings.
   - see =init-keys.el= to see normal keyboard bindings

** Why is this insanely configured?

   This is configured for me. If you don't like this, this is not for you.

* License

  Copyright (c) 2016 Mohammed Sadiq <sadiq@sadiqpk.org>

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but *without any warranty*; without even the implied warranty of
  *merchantability* or *fitness for a particular purpose*.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see [[http://www.gnu.org/licenses/]].
